# Generated by Django 5.1.7 on 2025-03-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sale_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="register_number",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
