# Generated by Django 5.1.7 on 2025-03-13 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_register_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("company_name", models.CharField(default="Mercato", max_length=255)),
                (
                    "company_cnpj",
                    models.CharField(default="10.100.100/0001-10", max_length=18),
                ),
                (
                    "client_name",
                    models.CharField(default="Consumidor Final", max_length=255),
                ),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="core.sale",
                    ),
                ),
            ],
        ),
    ]
