# Generated by Django 5.1.7 on 2025-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fakeinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="fakeinvoice",
            name="access_key",
            field=models.CharField(blank=True, max_length=44, unique=True),
        ),
        migrations.AddField(
            model_name="fakeinvoice",
            name="company_address",
            field=models.CharField(
                default="Rua Líbero Badaró, Taquara, Rio de Janeiro - CEP: 22713-110",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="fakeinvoice",
            name="company_email",
            field=models.EmailField(default="contato@mercato.com.br", max_length=254),
        ),
        migrations.AddField(
            model_name="fakeinvoice",
            name="company_legal_name",
            field=models.CharField(
                default="Mercato Software e Mercados LTDA", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="fakeinvoice",
            name="company_phone",
            field=models.CharField(default="(21) 12345-6789", max_length=20),
        ),
        migrations.AddField(
            model_name="fakeinvoice",
            name="company_state_registration",
            field=models.CharField(default="987654321", max_length=20),
        ),
        migrations.AddField(
            model_name="fakeinvoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name="fakeinvoice",
            name="protocol",
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="fakeinvoice",
            name="company_cnpj",
            field=models.CharField(default="00.000.000/0000-00", max_length=18),
        ),
        migrations.AlterField(
            model_name="fakeinvoice",
            name="company_name",
            field=models.CharField(default="Mercato Supermercado", max_length=255),
        ),
    ]
