# Generated by Django 5.1.7 on 2025-03-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_fakeinvoice_access_key_fakeinvoice_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fakeinvoice",
            name="company_cnpj",
            field=models.CharField(default="01.257.358/0001-67", max_length=18),
        ),
    ]
